### ISSUE TITLE
Another Request: automatically play  audio for feedback

### ISSUE THREAD

**Issue by valuex** [warleysr/ankipa#2]
Is it Okay to add one option? That is to automatically play some audio like good, excellent as a feedback after he/she finishes the recording and get a good score. That would be great for the young language learners.

**Comment by warleysr** [comment]
I added this in 89a83ee, but instead of playing some voice saying "good" I implemented sound effects. You can change the audio files if you want going into addon's folder and replacing the .mp3 files in **sounds** folder. You also need to enable this option on settings.
![image](https://user-images.githubusercontent.com/6331012/204374165-537dba6f-daa9-4094-baa5-10cb9fed0548.png)

The sound effect is based on overall pronunciation score:

```
< 30%      ===>    "low.mp3"
< 50%      ===>    "medium-low.mp3"
< 70%      ===>    "medium-high.mp3"
>= 70%     ===>    "high.mp3"
```
